const $=s=>document.querySelector(s), modal=$('#customize'),talk=$('#conversation');
let looks=[{hair:0,hairColor:'#754d36',eyeColor:'#795137',outfit:0},{hair:2,hairColor:'#27252d',eyeColor:'#459675',outfit:1}],party=1,editing=0,active=0,playing=false,room='garden',positions=[{x:50,y:86},{x:44,y:90}],target=null,near=null,last=0,ceremonyStart=null;const held=new Set();
function atlasPart(x,y,w,h,left,top,width,height,filter='',cls=''){return `<div class="avatar-layer ${cls}" style="left:${left}%;top:${top}%;width:${width}%;height:${height}%;background-size:${1182/w*100}% ${1330/h*100}%;background-position:${x/(1182-w)*100}% ${y/(1330-h)*100}%;filter:${filter||'none'}"></div>`}
const colorAtlas=new Image(),tintedCache=new Map();let atlasReady=false;
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16))}
function tintPixel(pixel,color){const light=(pixel[0]+pixel[1]+pixel[2])/3;return color.map(c=>Math.round(light<=140?c*light/140:c+(255-c)*(light-140)/115))}
function isIris(x,y){return ((x-42)/15)**2+((y-53)/21)**2<=1||((x-126)/15)**2+((y-53)/21)**2<=1}
function coloredPart(kind,variant,hex){const key=kind+variant+hex;if(tintedCache.has(key))return tintedCache.get(key);const hair=kind==='hair',w=hair?290:170,h=hair?330:90,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(colorAtlas,hair?[155,448,736,1025][variant]-145:940,hair?535:985,w,h,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h),color=rgb(hex);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,p=pixels.data;if(!p[i+3])continue;const light=(p[i]+p[i+1]+p[i+2])/3;if(light<32)continue;if(!hair&&(!isIris(x,y)||light>=180))continue;const out=tintPixel([p[i],p[i+1],p[i+2]],color);p[i]=out[0];p[i+1]=out[1];p[i+2]=out[2]}ctx.putImageData(pixels,0,0);const url=canvas.toDataURL();if(tintedCache.size>128)tintedCache.clear();tintedCache.set(key,url);return url}
function colorLayer(url,left,top,width,height,cls){return `<div class="avatar-layer ${cls}" style="left:${left}%;top:${top}%;width:${width}%;height:${height}%;background-image:url('${url}');background-size:100% 100%"></div>`}
function avatar(el,look){const centers=[155,448,736,1025],hairTop=[-36,-48,-38,-34][look.hair]/445*100;el.innerHTML=atlasPart(centers[look.outfit]-145,60,290,445,0,0,100,100)+(atlasReady?colorLayer(coloredPart('hair',look.hair,look.hairColor),0,hairTop,100,330/445*100,'hair-layer')+colorLayer(coloredPart('eyes',0,look.eyeColor),74/290*100,67/445*100,142/290*100,75/445*100,'eyes-layer'):atlasPart(centers[look.hair]-145,535,290,330,0,hairTop,100,330/445*100,'','hair-layer')+atlasPart(940,985,170,90,74/290*100,67/445*100,142/290*100,75/445*100,'','eyes-layer'))}
colorAtlas.onload=()=>{atlasReady=true;appearance()};colorAtlas.src='customization.png';

function appearance(){avatar($('#previewAvatar'),looks[editing]);avatar($('#playerAvatar'),looks[0]);avatar($('#companionAvatar'),looks[1]);$('#hair').value=looks[editing].hair;$('#outfit').value=looks[editing].outfit;document.querySelectorAll('[data-edit]').forEach(b=>b.classList.toggle('active',+b.dataset.edit===editing));for(const key of ['hairColor','eyeColor']){$('#'+key).value=looks[editing][key];$('#'+key+'Hex').value=looks[editing][key]}$('#lookTitle').textContent=party===2?(editing===0?'挑選你的婚禮造型':'挑選夥伴的婚禮造型'):'挑選你的婚禮造型'}
for(const key of ['hairColor','eyeColor']){const picker=$('#'+key),hex=$('#'+key+'Hex');picker.addEventListener('input',e=>{looks[editing][key]=e.target.value;appearance()});hex.addEventListener('input',e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value)){looks[editing][key]=e.target.value.toLowerCase();appearance()}});hex.addEventListener('change',()=>{hex.value=looks[editing][key]})}
for(const key of ['hair','outfit'])$('#'+key).onchange=e=>{looks[editing][key]=+e.target.value;appearance()};
document.querySelectorAll('[data-party]').forEach(b=>b.onclick=()=>{party=+b.dataset.party;editing=0;active=0;$('#partyStep').hidden=true;$('#lookStep').hidden=false;$('#editTabs').hidden=party!==2;$('#companion').hidden=party!==2;$('#switchPlayer').hidden=party!==2;appearance();render()});
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=+b.dataset.edit;appearance()});$('#back').onclick=()=>{$('#partyStep').hidden=false;$('#lookStep').hidden=true};
modal.addEventListener('cancel',e=>{if(!playing)e.preventDefault()});$('#closet').onclick=()=>{if(ceremonyStart!==null)return;held.clear();target=null;$('#partyStep').hidden=true;$('#lookStep').hidden=false;$('#editTabs').hidden=party!==2;$('#start').textContent='換好造型，回到婚禮 →';appearance();modal.showModal()};
let audioCtx,musicGain,musicOn=false,musicTimer;const musicSources=new Set();
// A short original synthesized arrangement of the public-domain Bridal Chorus.
const melody=[['G4',1],['C5',1.5],['C5',.5],['C5',2],['G4',1],['D5',1.5],['B4',.5],['C5',2],['G4',1],['C5',1.5],['F5',.5],['F5',1],['E5',1],['D5',1],['C5',1],['D5',2],['G4',1],['C5',1.5],['C5',.5],['C5',2],['G4',1],['D5',1.5],['B4',.5],['C5',2],['G4',1],['C5',1],['E5',1],['G5',1],['E5',1],['C5',1],['A4',1],['B4',1],['C5',3]];
function frequency(note){const m=note.match(/([A-G])([0-9])/),semitones={C:-9,D:-7,E:-5,F:-4,G:-2,A:0,B:2};return 440*2**((semitones[m[1]]+(+m[2]-4)*12)/12)}
function tone(f,t,d,volume){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.04);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(musicGain);musicSources.add(o);o.onended=()=>musicSources.delete(o);o.start(t);o.stop(t+d+.03)}
function musicPhrase(){if(!musicOn)return;let t=audioCtx.currentTime+.1;melody.forEach(([n,b],i)=>{const d=b*.44;tone(frequency(n),t,d*.95,.16);if(i%3===0){tone(frequency('C4')/2,t,d,.055);tone(frequency('E4'),t,d,.025)}t+=d});musicTimer=setTimeout(musicPhrase,(t-audioCtx.currentTime)*1000+900)}
async function startMusic(){try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();musicGain=audioCtx.createGain();musicGain.connect(audioCtx.destination)}await audioCtx.resume();if(!musicOn){musicOn=true;musicGain.gain.value=.65;musicPhrase()}$('#sound').textContent='♫';$('#sound').setAttribute('aria-label','關閉音樂');$('#sound').setAttribute('aria-pressed','true')}catch{notify('點上方音符可再試一次播放音樂')}}
$('#sound').onclick=()=>{if(musicOn){musicOn=false;clearTimeout(musicTimer);musicSources.forEach(o=>{try{o.stop()}catch{}});musicSources.clear();musicGain.gain.value=0;$('#sound').textContent='♪';$('#sound').setAttribute('aria-label','開啟音樂');$('#sound').setAttribute('aria-pressed','false')}else startMusic()};
$('#start').onclick=()=>{modal.close();appearance();if(!playing){playing=true;startMusic();beginCeremony()}else render()};
function beginCeremony(){switchRoom('garden');positions=[{x:50,y:86},{x:44,y:90}];ceremonyStart=performance.now();held.clear();target=null;$('.app').classList.add('in-ceremony');$('#ceremony').hidden=false;$('#bear').hidden=true;$('#player').hidden=true;$('#companion').hidden=true;$('#groom').style.left='45%';$('#bride').style.left='55%';$('#bride').style.top='82%';$('#bride').classList.add('walking');$('#ceremonyText').textContent='請迎接新娘'}
function finishCeremony(){$('#leaveWedding').disabled=false;ceremonyStart=null;$('.app').classList.remove('in-ceremony');$('#ceremony').hidden=true;$('#ceremony').classList.remove('kiss-mode');$('#kiss').hidden=true;$('#hearts').hidden=true;$('#groom').hidden=false;$('#bride').hidden=false;$('#bear').hidden=false;$('#player').hidden=false;$('#companion').hidden=party!==2;$('#bride').classList.remove('walking');$('#bride').style.left='57%';$('#bride').style.top='24%';$('#groom').style.left='45%';$('#state').textContent='禮成，歡迎一起慶祝';render()}
$('#skip').onclick=finishCeremony;
function ceremonyFrame(t){const elapsed=(t-ceremonyStart)/1000;if(elapsed<8){$('#bride').style.top=(82-elapsed/8*58)+'%'}else if(elapsed<10){$('#ceremonyText').textContent='從今天起，與你相伴';$('#bride').classList.remove('walking');$('#bride').style.left=(55-(elapsed-8)*3)+'%';$('#groom').style.left=(45+(elapsed-8)*1.5)+'%'}else if(elapsed<18){$('#ceremony').classList.add('kiss-mode');$('#ceremonyText').textContent='以一個吻，許下永遠';$('#bride').hidden=true;$('#groom').hidden=true;$('#kiss').hidden=false;$('#hearts').hidden=false}else finishCeremony()}
const places={garden:[{x:45,y:29,r:12,name:'伊薩克',art:'special mature',text:'歡迎。',action:'送上新婚祝福 ♡'},{x:57,y:29,r:12,name:'白暝',art:'sprite s1',text:'歡迎來到我們的婚禮～',action:'送上新婚祝福 ♡'},{x:79,y:37,r:13,name:'鮑里斯',art:'special boris',text:'「嗚！」四肢著地的鮑里斯抬起頭，輕輕嗅了嗅空氣，脖子上的藍色蝴蝶結也跟著晃了晃。',action:'向鮑里斯打招呼 ♡'},{x:22,y:72,r:15,name:'花園蛋糕',text:'小巧的藍白奶油花，藏著甜甜的心意。宴會廳裡還有大婚禮蛋糕等著你！',action:'品嚐一小口 ♡'}],hall:[{x:50,y:49,r:17,name:'大結婚蛋糕',text:'層層白色奶油綴著藍色花朵，這座大蛋糕是今天最甜蜜的主角。一起分享伊薩克與白暝的幸福吧。',action:'享用婚禮蛋糕 ♡'},{x:19,y:33,r:12,name:'花好月圓（炸湯圓）',text:'粉紅與金黃的小湯圓炸得外酥內軟，撒上香甜花生粉。花好月圓，祝新人團團圓圓、甜甜蜜蜜！',action:'品嚐花好月圓 ♡'},{x:83,y:34,r:13,name:'婚宴佳餚',text:'香烤雞肉、鮮蝦與熱騰騰的料理已經上桌，為今天的相聚添上豐盛的滋味。',action:'享用美食 ♡'},{x:83,y:55,r:14,name:'水果與甜點',text:'繽紛水果、精緻小蛋糕與甜點擺滿了餐桌，挑一份喜歡的，慢慢享用吧。',action:'拿一份甜點 ♡'}]};
function switchRoom(next){room=next;held.clear();target=null;$('#map').src=room==='garden'?'garden.png':'banquet.png';$('#map').alt=room==='garden'?'藍白花園婚禮':'室內宴會廳，中央大結婚蛋糕與兩側美食餐桌';$('#roomName').textContent=room==='garden'?'藍色花園':'室內宴會廳';for(const id of ['groom','bride','bear'])$('#'+id).hidden=room!=='garden';$('#portal').textContent=room==='garden'?'宴會廳 →':'← 主會場';$('#portal').classList.toggle('return',room==='hall');if(playing){positions=room==='hall'?[{x:16,y:55},{x:18,y:62}]:[{x:84,y:54},{x:79,y:59}]}render()}
$('#portal').onclick=e=>{e.stopPropagation();if(ceremonyStart===null)switchRoom(room==='garden'?'hall':'garden')};$('#portal').onpointerdown=e=>e.stopPropagation();
$('#switchPlayer').onclick=()=>{active=1-active;target=null;held.clear();$('#switchPlayer').textContent='目前：'+(active===0?'你':'夥伴')+' ↔';render()};
function render(){['player','companion'].forEach((id,i)=>{const p=$('#'+id);p.style.left=positions[i].x+'%';p.style.top=positions[i].y+'%';p.querySelector('span').textContent=i===0?'你':'同行夥伴';let pointer=p.querySelector('.pointer');if(pointer)pointer.remove();if(active===i){pointer=document.createElement('div');pointer.className='pointer';pointer.textContent='▼';p.prepend(pointer)}});const pos=positions[active];near=places[room].map(o=>({...o,d:Math.hypot(pos.x-o.x,pos.y-o.y)})).filter(o=>o.d<o.r).sort((a,b)=>a.d-b.d)[0];$('#interact').disabled=!near;$('#location').textContent=room==='hall'?'婚宴時光':pos.y<40?'誓約花亭':pos.y<68?'藍色花道':'花園入口';$('#hint').textContent=near?'點「互動」：'+near.name:room==='garden'?'往右可以前往室內宴會廳':'走近餐桌，品嚐婚宴美食'}
function openTalk(){if(!near||modal.open||talk.open||ceremonyStart!==null)return;held.clear();target=null;$('#speaker').textContent=near.name;$('#speakerArt').className=near.art||'';$('#speech').textContent=near.text;$('#reply').textContent=near.action;talk.showModal()}
$('#interact').onclick=openTalk;$('#closeTalk').onclick=()=>talk.close();let toastTimer;function notify(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800)}$('#reply').onclick=()=>{talk.close();$('#state').textContent='♡ 幸福，有你一份';notify(near?.name==='鮑里斯'?'鮑里斯開心地晃了晃藍色蝴蝶結 ♡':room==='hall'||near?.name==='花園蛋糕'?'一口甜蜜，幸福滿滿 ♡':'你的祝福，已送達新人心裡 ♡')};
document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.add(b.dataset.dir);target=null};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>held.delete(b.dataset.dir)});
const keys={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};window.addEventListener('keydown',e=>{if(modal.open||talk.open||$('#farewell').open||ceremonyStart!==null)return;if(keys[e.key]){e.preventDefault();held.add(keys[e.key]);target=null}if(e.key===' '||e.key==='Enter'){e.preventDefault();openTalk()}});window.addEventListener('keyup',e=>held.delete(keys[e.key]));window.addEventListener('blur',()=>held.clear());document.addEventListener('visibilitychange',()=>held.clear());
$('#world').onpointerdown=e=>{if(!playing||modal.open||talk.open||ceremonyStart!==null)return;const r=$('#world').getBoundingClientRect();target={x:Math.max(10,Math.min(93,(e.clientX-r.left)/r.width*100)),y:Math.max(28,Math.min(94,(e.clientY-r.top)/r.height*100))}};
function step(t){const dt=Math.min((t-last)/1000,.035);last=t;let dx=0,dy=0;if(ceremonyStart!==null)ceremonyFrame(t);else if(playing&&!modal.open&&!talk.open){dx=(held.has('right')?1:0)-(held.has('left')?1:0);dy=(held.has('down')?1:0)-(held.has('up')?1:0);const pos=positions[active];if(target&&!dx&&!dy){const a=target.x-pos.x,b=target.y-pos.y,d=Math.hypot(a,b);if(d<.8)target=null;else{dx=a/d;dy=b/d}}if(dx||dy){const len=Math.hypot(dx,dy);pos.x=Math.max(7,Math.min(95,pos.x+dx/len*25*dt));pos.y=Math.max(28,Math.min(94,pos.y+dy/len*25*dt));if(party===2){const partner=positions[1-active],dist=Math.hypot(pos.x-partner.x,pos.y-partner.y);if(dist>9){partner.x+=(pos.x-partner.x)/dist*23*dt;partner.y+=(pos.y-partner.y)/dist*23*dt}}if(room==='garden'&&pos.x>93&&pos.y>43&&pos.y<63)switchRoom('hall');else if(room==='hall'&&pos.x<9&&pos.y>43&&pos.y<63)switchRoom('garden');render()}}['player','companion'].forEach((id,i)=>$('#'+id).classList.toggle('walking',!!(dx||dy)&&(i===active||party===2)));requestAnimationFrame(step)}
$('#companion').hidden=true;appearance();render();modal.showModal();requestAnimationFrame(step);

// The souvenir uses the same selected sprite layers as the live guests.
const farewell=$('#farewell');let photoUrl=null,photoRun=0,resumeMusic=false;
function loadPhotoImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('照片素材未能載入'));im.src=src})}
async function composeSouvenir(snapshot,count){
 const [garden,groom,bride,atlas]=await Promise.all(['photo-stage.png','isaac.png','characters.png','customization.png'].map(loadPhotoImage));
 if(!atlasReady){await colorAtlas.decode();atlasReady=true}
 await document.fonts.load('72px WeddingScript');
 const guestLayers=await Promise.all(snapshot.slice(0,count).map(async look=>({hair:await loadPhotoImage(coloredPart('hair',look.hair,look.hairColor)),eyes:await loadPhotoImage(coloredPart('eyes',0,look.eyeColor))})));
 const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1200;const ctx=canvas.getContext('2d');ctx.fillStyle='#fdfefe';ctx.fillRect(0,0,1080,1200);ctx.imageSmoothingEnabled=false;
 ctx.drawImage(garden,0,0,garden.naturalWidth,garden.naturalHeight,40,40,1000,840);
 ctx.fillStyle='#ecf5fc';ctx.fillRect(40,890,1000,270);ctx.strokeStyle='#99b9d6';ctx.lineWidth=3;ctx.strokeRect(23,23,1034,1154);
 const centers=count===2?[200,880]:[300];
 // Newlyweds stand together at the centre, guests alongside them.
 const groomCenter=count===2?425:530,brideCenter=count===2?655:745;
 const groomHeight=count===2?550:570,groomWidth=groomHeight*530/1220,brideHeight=count===2?520:540,brideWidth=brideHeight*.75;
 ctx.drawImage(groom,360,10,530,1220,groomCenter-groomWidth/2,860-groomHeight,groomWidth,groomHeight);
 ctx.drawImage(bride,384,0,384,512,brideCenter-brideWidth/2,860-brideHeight,brideWidth,brideHeight);
 for(let i=0;i<count;i++){const look=snapshot[i],scale=count===2?1.07:1.18,x=centers[i]-290*scale/2,y=860-445*scale;ctx.drawImage(atlas,[155,448,736,1025][look.outfit]-145,60,290,445,x,y,290*scale,445*scale);ctx.drawImage(guestLayers[i].eyes,x+74*scale,y+67*scale,142*scale,75*scale);ctx.drawImage(guestLayers[i].hair,x,y+[-36,-48,-38,-34][look.hair]*scale,290*scale,330*scale)}
 ctx.imageSmoothingEnabled=true;ctx.fillStyle='#315d88';ctx.textAlign='center';ctx.font='72px WeddingScript';const message='Thank you for your blessings.';if(ctx.measureText(message).width>960)ctx.font='60px WeddingScript';ctx.fillText(message,540,997);ctx.font='28px Georgia, serif';ctx.fillText('Isaac & Baiming',540,1060);ctx.font='18px Georgia, serif';ctx.fillStyle='#7d9bb6';ctx.fillText('A LITTLE BLUE WEDDING',540,1113);
 return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('照片未能產生')),'image/png'));
}
async function generatePhoto(){const run=++photoRun,snapshot=looks.map(l=>({...l})),count=party;$('#photoStatus').textContent='正在準備你的紀念合照…';$('#photoStatus').hidden=false;$('#souvenir').hidden=true;$('#downloadPhoto').hidden=true;$('#saveTip').hidden=true;$('#retryPhoto').hidden=true;try{const blob=await composeSouvenir(snapshot,count);if(run!==photoRun||!farewell.open)return;if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(blob);$('#souvenir').src=photoUrl;$('#souvenir').hidden=false;$('#downloadPhoto').href=photoUrl;$('#downloadPhoto').hidden=false;$('#saveTip').hidden=false;$('#photoStatus').textContent='感謝你的祝福。願這張合照，留下今天的美好。'}catch{if(run!==photoRun)return;$('#photoStatus').textContent='照片暫時未能完成，請再試一次。你的造型仍然保留。';$('#retryPhoto').hidden=false}}
$('#leaveWedding').onclick=()=>{if(!playing||ceremonyStart!==null)return;held.clear();target=null;playing=false;resumeMusic=musicOn;if(musicOn)$('#sound').click();farewell.showModal();generatePhoto()};
$('#retryPhoto').onclick=generatePhoto;
function returnToWedding(){photoRun++;farewell.close();playing=true;held.clear();if(resumeMusic)startMusic()}
$('#returnWedding').onclick=returnToWedding;farewell.addEventListener('cancel',e=>{e.preventDefault();returnToWedding()});
