// A device-local card: no network requests or shared records.
const stickerTypes=[['heart',0,'愛心'],['flower',1,'花花'],['bear',2,'小熊'],['ribbon',3,'蝴蝶結'],['star',4,'星星'],['dove',5,'白鴿']];
function stickerIcon(type){const s=document.createElement('span');s.className='pixel-sticker';s.style.backgroundPosition=(type[1]%3*50)+'% '+Math.floor(type[1]/3)*100+'%';s.setAttribute('aria-hidden','true');return s}
const boardCanvas=$('#freeBoard'),boardCtx=boardCanvas.getContext('2d'),boardAtlas=new Image();let boardItems=[],boardMessage='',selectedKind='heart',selectedId=null,boardHistory=[],boardDrag=null,boardUrl=null,boardOwner='';
try{const saved=JSON.parse(localStorage.getItem('wedding-local-card-v1')||'null');if(saved){boardItems=Array.isArray(saved.items)?saved.items.filter(i=>stickerTypes.some(t=>t[0]===i.kind)&&Number.isFinite(i.x)&&Number.isFinite(i.y)).slice(0,100).map(i=>({...i,x:Math.max(.06,Math.min(.94,i.x)),y:Math.max(.06,Math.min(.94,i.y))})):[];boardMessage=String(saved.message||'').slice(0,180);boardOwner=String(saved.owner||'').slice(0,16)}}catch{}
$('#boardMessage').value=boardMessage;
function boardCheckpoint(){boardHistory.push(JSON.stringify({items:boardItems,message:boardMessage}));if(boardHistory.length>30)boardHistory.shift()}
function storeBoard(){try{localStorage.setItem('wedding-local-card-v1',JSON.stringify({items:boardItems,message:boardMessage,owner:boardOwner}));$('#boardStatus').textContent='已儲存在這台裝置，可完成後下載圖片。'}catch{$('#boardStatus').textContent='瀏覽器無法儲存，請下載圖片保留作品。'}$('#boardDownload').hidden=true;$('#boardPreview').hidden=true}
function lines(ctx,text,maxWidth){const result=[];let line='';for(const letter of text){if(letter==='\n'){result.push(line);line='';continue}if(ctx.measureText(line+letter).width>maxWidth){result.push(line);line=letter}else line+=letter}result.push(line);return result}
function drawBoard(selection=true){const g=boardCtx;g.clearRect(0,0,800,1000);g.fillStyle='#f7fbff';g.fillRect(0,0,800,1000);g.strokeStyle='#9bbbd9';g.lineWidth=7;g.strokeRect(22,22,756,956);g.fillStyle='#315d88';g.textAlign='center';g.font='30px Georgia,serif';g.fillText('A Little Wedding Blessing',400,80);g.font='22px sans-serif';g.fillText('伊薩克 ＆ 白冥',400,121);g.fillStyle='#e5f0fa';g.fillRect(45,605,710,317);g.fillStyle='#315d88';let messageSize=36;g.font=messageSize+'px sans-serif';let wrapped=lines(g,boardMessage,650);while(wrapped.length*(messageSize+7)>280&&messageSize>28){messageSize-=2;g.font=messageSize+'px sans-serif';wrapped=lines(g,boardMessage,650)}if(wrapped.length*(messageSize+7)>280)wrapped=lines(g,boardMessage.replace(/\n+/g,' '),650);g.textBaseline='middle';const firstLineY=763.5-(wrapped.length-1)*(messageSize+7)/2;wrapped.forEach((line,i)=>g.fillText(line,400,firstLineY+i*(messageSize+7)));g.textBaseline='alphabetic';g.font='20px sans-serif';g.fillText('WITH LOVE · '+boardOwner,400,953,690);g.imageSmoothingEnabled=false;
 for(const item of boardItems){const index=stickerTypes.find(t=>t[0]===item.kind)[1],x=item.x*800,y=item.y*1000;if(boardAtlas.complete&&boardAtlas.naturalWidth)g.drawImage(boardAtlas,index%3*512,Math.floor(index/3)*512,512,512,x-48,y-48,96,96);if(selection&&selectedId===item.id){g.strokeStyle='#477eaf';g.lineWidth=2;g.setLineDash([5,4]);g.strokeRect(x-47,y-47,94,94);g.setLineDash([])}}}
boardAtlas.onload=()=>drawBoard();boardAtlas.onerror=()=>{$('#boardStatus').textContent='貼紙素材未能載入，請重新整理後再試。'};boardAtlas.src='wedding-stickers.png';
stickerTypes.forEach(t=>{const b=document.createElement('button');b.type='button';b.dataset.sticker=t[0];b.append(stickerIcon(t));b.setAttribute('aria-label',t[2]);b.setAttribute('aria-pressed',selectedKind===t[0]);b.onclick=()=>{selectedKind=t[0];selectedId=null;document.querySelectorAll('[data-sticker]').forEach(el=>el.setAttribute('aria-pressed',el.dataset.sticker===selectedKind));drawBoard()};$('#stickerPalette').append(b)});
function boardPoint(e){const r=boardCanvas.getBoundingClientRect();return{x:Math.max(.06,Math.min(.94,(e.clientX-r.left)/r.width)),y:Math.max(.06,Math.min(.94,(e.clientY-r.top)/r.height))}}
boardCanvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const p=boardPoint(e);const hit=[...boardItems].reverse().find(i=>Math.abs(i.x-p.x)<.06&&Math.abs(i.y-p.y)<.048);boardCheckpoint();if(hit){selectedId=hit.id;boardDrag={id:hit.id,dx:hit.x-p.x,dy:hit.y-p.y}}else{if(boardItems.length>=100){$('#boardStatus').textContent='這張卡片已有 100 張貼紙，先刪除一些再加入。';return}const item={id:crypto.randomUUID(),kind:selectedKind,...p};boardItems.push(item);selectedId=item.id;boardDrag={id:item.id,dx:0,dy:0}}boardCanvas.setPointerCapture(e.pointerId);drawBoard()};
boardCanvas.onpointermove=e=>{if(!boardDrag)return;const item=boardItems.find(i=>i.id===boardDrag.id),p=boardPoint(e);if(item){item.x=Math.max(.06,Math.min(.94,p.x+boardDrag.dx));item.y=Math.max(.06,Math.min(.94,p.y+boardDrag.dy));drawBoard()}};
function finishDrag(){if(!boardDrag)return;boardDrag=null;storeBoard();drawBoard()}boardCanvas.onpointerup=boardCanvas.onpointercancel=boardCanvas.onlostpointercapture=finishDrag;
$('#boardMessage').onfocus=boardCheckpoint;$('#boardMessage').oninput=()=>{boardMessage=$('#boardMessage').value;storeBoard();drawBoard()};
$('#undoSticker').onclick=()=>{if(!boardHistory.length)return;const old=JSON.parse(boardHistory.pop());boardItems=old.items;boardMessage=old.message;$('#boardMessage').value=boardMessage;selectedId=null;storeBoard();drawBoard()};$('#deleteSticker').onclick=()=>{if(!selectedId)return;boardCheckpoint();boardItems=boardItems.filter(i=>i.id!==selectedId);selectedId=null;storeBoard();drawBoard()};$('#clearBoard').onclick=()=>{boardCheckpoint();boardItems=[];boardMessage='';$('#boardMessage').value='';selectedId=null;storeBoard();drawBoard()};
$('#saveBoard').onclick=()=>{if(!boardAtlas.complete||!boardAtlas.naturalWidth){$('#boardStatus').textContent='請等貼紙素材載入後再試。';return}drawBoard(false);boardCanvas.toBlob(blob=>{drawBoard();if(!blob){$('#boardStatus').textContent='圖片產生失敗，請再試一次。';return}if(boardUrl)URL.revokeObjectURL(boardUrl);boardUrl=URL.createObjectURL(blob);$('#boardDownload').href=boardUrl;$('#boardDownload').hidden=false;$('#boardPreview').src=boardUrl;$('#boardPreview').hidden=false;$('#boardStatus').textContent='圖片已完成，可以下載或長按圖片儲存。'},'image/png')};
function openStickerBoard(){if(!playing||ceremonyStart!==null||modal.open||talk.open||momentDialog.open||momentBusy)return;target=null;held.clear();boardOwner=guestName(active);$('#stickerDialog').showModal();drawBoard();storeBoard()}
$('#blessingBoard').onpointerdown=e=>e.stopPropagation();$('#blessingBoard').onclick=e=>{e.stopPropagation();openStickerBoard()};$('#closeStickers').onclick=()=>{finishDrag();$('#stickerDialog').close()};
// All family members are included, in fixed poses, on the stage.
composeSouvenir=async function(snapshot,count){
 const [stage,groom,bride,kids,bear,stickers]=await Promise.all(['photo-stage.png','isaac.png','characters.png','flower-children-chibi.png','boris.png','wedding-stickers.png'].map(loadPhotoImage));await document.fonts.load('72px WeddingScript');
 const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1200;const g=canvas.getContext('2d');g.fillStyle='#fdfefe';g.fillRect(0,0,1080,1200);g.imageSmoothingEnabled=false;g.drawImage(stage,0,0,stage.naturalWidth,stage.naturalHeight,40,40,1000,840);g.fillStyle='#ecf5fc';g.fillRect(40,890,1000,270);g.strokeStyle='#99b9d6';g.lineWidth=3;g.strokeRect(23,23,1034,1154);
 const ground=700,groomHeight=500*1192/1220,brideHeight=480*466/512,groomX=465,brideX=715;
 g.drawImage(groom,383,24,479,1192,groomX-groomHeight*479/1192/2,ground-groomHeight,groomHeight*479/1192,groomHeight);
 g.drawImage(bride,408,44,358,466,brideX-brideHeight*358/466/2,ground-brideHeight,brideHeight*358/466,brideHeight);
 const centers=count===2?[175,930]:[195];for(let i=0;i<count;i++){const sprite=guestSprite({...snapshot[i],pose:'stand'}),height=guestHeight(snapshot[i],groomHeight,brideHeight),width=height*sprite.width/sprite.height;g.drawImage(sprite.canvas,centers[i]-width/2,ground-height,width,height);if(memories.flower)g.drawImage(stickers,512,0,512,512,centers[i]+18,ground-height*.56,34,34)}
 const childTop=ground-groomHeight*.61,childHeight=ground-childTop;
 g.drawImage(kids,28,19,728,967,370-childHeight*728/967/2,childTop,childHeight*728/967,childHeight);
 g.drawImage(kids,812,67,710,931,560-childHeight*710/931/2,childTop,childHeight*710/931,childHeight);
 const bearWidth=350,bearHeight=bearWidth*bear.naturalHeight/bear.naturalWidth;g.drawImage(bear,1020-bearWidth,865-bearHeight,bearWidth,bearHeight);
 g.imageSmoothingEnabled=true;g.fillStyle='#315d88';g.textAlign='center';g.font='72px WeddingScript';const message='Thank you for your blessings.';if(g.measureText(message).width>960)g.font='60px WeddingScript';g.fillText(message,540,997);g.font='28px Georgia,serif';g.fillText('Isaac & Baiming',540,1057);for(let i=0;i<count;i++){g.font='25px sans-serif';g.fillText('WITH  '+(snapshot[i].name?.trim()||(i===0?'你':'同行夥伴')),540,count===1?1100:1088+32*i,920)}g.fillStyle='#7d9bb6';g.font='18px Georgia,serif';g.fillText('A LITTLE BLUE WEDDING',540,1150);
 return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('合照產生失敗')),'image/png'))
};
const boxButton=document.createElement('button');boxButton.id='openMemoryBox';boxButton.textContent='▣ 紀念盒';$('#momentTray').append(boxButton);
function collectedItems(){return[
 memories.flower&&{icon:1,name:'薩維里的小白花',text:'他從花籃認真挑選，親手送給你的一朵花。'},
 memories.petals&&{icon:1,name:'藍白花瓣',text:'和狄安娜一起撒花時，留下的一小把幸福。'},
 memories.bear&&{icon:2,name:'鮑里斯的友誼',text:'餵食或摸摸後，收到的小熊友誼徽章。'},
 memories.ribbon===3&&{icon:3,name:'藍緞帶紀念結',text:'幫孩子找回緞帶後，他們送你的蝴蝶結。'},
 memories.fortune&&{icon:4,name:'你的花籤',text:memories.fortune+'。'},
 memories.cake&&{icon:0,name:'婚禮蛋糕小卡',text:'你和新人分享了綴著'+memories.cake+'的蛋糕。'},
 memories.toast&&{icon:5,name:'碰杯紀念',text:'把今天的幸福，分享給身旁的人。'}
 ].filter(Boolean)}
boxButton.onclick=()=>{if(!freeScene())return;const items=collectedItems();story('你的婚禮紀念盒',items.length?'打開盒子，看看今天收集到的小幸福。':'盒子還空著。陪孩子玩耍、餵鮑里斯、抽花籤或參加切蛋糕，就能收集紀念品。');const box=document.createElement('div');box.className='memory-box';const lid=document.createElement('div');lid.className='memory-box-lid';lid.textContent='A LITTLE BOX OF LOVE';box.append(lid);const inside=document.createElement('div');inside.className='memory-box-inside';for(const item of items){const b=document.createElement('button');b.className='memory-item';b.append(stickerIcon(['',item.icon,'']));const name=document.createElement('span');name.textContent=item.name;b.append(name);b.onclick=()=>{$('#momentText').textContent=item.text};inside.append(b)}box.append(inside);$('#momentOptions').append(box);const hint=document.createElement('p');hint.className='box-note';hint.textContent='紀念盒記錄這次參加的任務，重新整理後會重新開始。';$('#momentOptions').append(hint)};
