// Small wedding stories belong to this visit, not shared sticker records.
const memories={flower:false,petals:false,bear:false,ribbon:0,fortune:null,cake:null,gift:'',toast:false};

let momentBusy=false,bubbleMode=false,ambientTick=0,brideChats=0,lastBell=0;
const momentTimers=new Set();
function later(fn,ms){const id=setTimeout(()=>{momentTimers.delete(id);fn()},ms);momentTimers.add(id);return id}
function freeScene(){return playing&&ceremonyStart===null&&!modal.open&&!talk.open&&!farewell.open&&!$('#stickerDialog').open&&!$('#momentDialog').open&&!momentBusy}
function addMomentButton(parent,label,fn){const b=document.createElement('button');b.type='button';b.className='moment-option';b.textContent=label;b.onclick=fn;parent.append(b);return b}
const momentDialog=document.createElement('dialog');momentDialog.id='momentDialog';momentDialog.innerHTML='<div class="eyebrow">LITTLE WEDDING STORIES</div><h2 id="momentTitle"></h2><p id="momentText"></p><div id="momentOptions"></div><button id="closeMoment" class="text-button">繼續逛逛</button>';document.body.append(momentDialog);
function story(title,text,options=[]){held.clear();target=null;$('#momentTitle').textContent=title;$('#momentText').textContent=text;$('#momentOptions').replaceChildren();options.forEach(([label,fn])=>addMomentButton($('#momentOptions'),label,fn));if(!momentDialog.open)momentDialog.showModal()}
$('#closeMoment').onclick=()=>momentDialog.close();
const fxLayer=document.createElement('div');fxLayer.id='momentFx';fxLayer.setAttribute('aria-hidden','true');$('.stage').append(fxLayer);
function burst(kind,x=50,y=50,n=12){for(let i=0;i<n;i++){const f=document.createElement('i');f.className='moment-fx '+kind;f.textContent=kind==='bubble'?'':kind==='petal'?'✿':kind==='heart'?'♡':'✦';f.style.cssText=`left:${x+(Math.random()-.5)*12}%;top:${y}%;--drift:${(Math.random()-.5)*130}px;--duration:${2+Math.random()*2}s`;fxLayer.append(f);later(()=>f.remove(),4200)}}
function animate(el,frames,duration=1800){return el.animate?.(frames,{duration,iterations:1,easing:'ease-in-out'})}
function wearFlower(){for(const id of ['player','companion']){const el=$('#'+id);if(!el.querySelector('.guest-flower')){const f=document.createElement('span');f.className='guest-flower';f.textContent='✿';el.append(f)}}}
const originalTalk=openTalk;
openTalk=function(){if(momentBusy||momentDialog.open)return;originalTalk();if(!talk.open)return;$('#extraActions')?.remove();const actions=document.createElement('div');actions.id='extraActions';$('#speech').after(actions);
 const add=(label,fn)=>addMomentButton(actions,label,()=>{talk.close();fn()});
 if(near?.name==='白冥'){if(brideChats++>0)$('#speech').textContent='「他今天看起來很冷靜，其實出門前確認了三次戒指。」伊薩克停頓了一下：「……兩次。」';add('看伊薩克替白冥整理頭紗',()=>coupleMoment('veil'));add('請伊薩克接過花束',()=>coupleMoment('bouquet'));add('邀請新人牽手散步',()=>tour())}
 if(near?.name==='伊薩克'){add('邀請新人牽手散步',()=>tour());add('和新人舉杯',()=>toastWith('新人'))}
 if(near?.child==='saviri'){add('收下薩維里的小白花',()=>{memories.flower=true;wearFlower();animate($('#saviri'),[{translate:'0 0'},{translate:'0 -4px'},{translate:'0 0'}]);story('薩維里的小白花','他認真挑了一朵完整的小白花，悄悄遞給你。「這朵……給你。」小花已別在你的衣服上，也會留在紀念照裡。')});add('問問他在看什麼',()=>ribbonStory());add('和孩子一起喝果汁',()=>toastWith('孩子'))}
 if(near?.child==='diana'){add('一起撒花',()=>{story('跟狄安娜一起撒花','「你看！花花飛起來了！」點一下，就和她一起撒花。',[['撒一把藍白花瓣',()=>{memories.petals=true;burst('petal',63,37,22);animate($('#diana'),[{translate:'0 0'},{translate:'0 -12px'},{translate:'0 0'}]);$('#momentText').textContent='狄安娜踮起腳，開心地晃晃尾巴：「再一次、再一次！」'}]])});add('幫她找藍緞帶',ribbonStory);add('和孩子一起喝果汁',()=>toastWith('孩子'))}
 if(near?.name==='鮑里斯'){add('摸摸頭',()=>petBear('head'));add('摸摸背',()=>petBear('back'));add('看看藍色蝴蝶結',()=>petBear('bow'))}
 if(near?.name==='大結婚蛋糕'){add('邀請新人一起切蛋糕',cutCake)}
};$('#interact').onclick=()=>openTalk();
const originalFeed=$('#feedBoris').onclick;$('#feedBoris').onclick=()=>{originalFeed();memories.bear=true;if(borisFeedCount===2)$('#speech').textContent+=' 鮑里斯又靠近了一點，輕輕聞聞你的手。';if(borisFeedCount>=3)$('#speech').textContent+=' 牠安心地伏低身體，等著你摸摸。';animate($('#bear'),[{scale:'1 1'},{scale:borisFeedCount>=3?'1.06 .85':'1.02 .96'},{scale:'1 1'}])};
function petBear(part){memories.bear=true;const words={head:'鮑里斯舒服地瞇起眼睛，鼻尖輕輕動了動。',back:'你順著毛摸摸牠的背，牠伏低身體，滿足地呼了一口氣。',bow:'你碰了碰藍色蝴蝶結，鮑里斯抬起頭，好奇地看著你。'};animate($('#bear'),[{rotate:'0deg',scale:'1 1'},{rotate:part==='bow'?'3deg':'-2deg',scale:part==='back'?'1.05 .85':'1 .95'},{rotate:'0deg',scale:'1 1'}]);notify(words[part])}
function ribbonStory(){if(memories.ribbon===0){memories.ribbon=1;$('#lostRibbon').hidden=room!=='garden';story('飄走的藍緞帶','狄安娜指著空空的小花籃：「我的緞帶飛走了！」薩維里小聲說：「花園……祝福板旁邊。」到花園找找看吧。')}else if(memories.ribbon===1)story('薩維里的提示','「在花園，白山茶的旁邊。」找到地上的藍緞帶，點一下就能拾起。');else if(memories.ribbon===2){memories.ribbon=3;story('一起說謝謝','狄安娜把緞帶繫回花籃，薩維里替她拉平蝴蝶結。「謝謝你！」兩個孩子一起抬頭看著你。');burst('heart',50,37,12)}else story('找回的小幸福','狄安娜晃晃修好的花籃，薩維里朝你輕輕點頭。')}
const ribbon=document.createElement('button');ribbon.id='lostRibbon';ribbon.className='scene-prop ribbon-prop';ribbon.hidden=true;ribbon.innerHTML='<span class="pixel-sticker" style="background-position:0% 100%"></span>';ribbon.setAttribute('aria-label','拾起藍緞帶');ribbon.onpointerdown=e=>e.stopPropagation();ribbon.onclick=e=>{e.stopPropagation();if(!freeScene())return;memories.ribbon=2;ribbon.hidden=true;notify('找到藍緞帶了！回宴會廳交給孩子們吧。')};$('#world').append(ribbon);
function coupleMoment(kind){if(!freeScene()||room!=='garden')return;momentBusy=true;target=null;const bride=$('#bride'),groom=$('#groom');const a=groom.animate?.([{translate:'0 0'},{translate:'18px 0',offset:.4},{translate:'18px 0',offset:.7},{translate:'0 0'}],{duration:3000});animate(bride,[{rotate:'0deg'},{rotate:'-3deg'},{rotate:'0deg'}],3000);burst('heart',51,22,5);notify(kind==='veil'?'伊薩克替白冥整理頭紗；她輕輕靠向他的手。':'伊薩克接過花束，另一隻手仍讓白冥牽著。');later(()=>{a?.cancel();momentBusy=false},3100)}
function tour(){if(!freeScene())return;momentBusy=true;target=null;const oldRoom=room;const g=$('#groom'),b=$('#bride');g.hidden=b.hidden=false;g.style.left='46%';b.style.left='56%';g.style.top=b.style.top=room==='hall'?'35%':'24%';g.classList.add('touring');b.classList.add('touring');notify(room==='hall'?'新人牽手來看孩子，白冥彎下身聽狄安娜說話。':'新人牽著手走下花道，準備到宴會廳看看孩子。');animate(g,[{translate:'0 0'},{translate:'0 90px'},{translate:'0 0'}],6500);animate(b,[{translate:'0 0'},{translate:'0 90px'},{translate:'0 0'}],6500);later(()=>{g.classList.remove('touring');b.classList.remove('touring');g.style.left='45%';b.style.left='57%';g.style.top=b.style.top='24%';g.hidden=b.hidden=room!=='garden';momentBusy=false;if(oldRoom==='garden'&&room==='garden'){notify('新人到宴會廳探望孩子；稍後就會回到花園。');visitingUntil=Date.now()+18000;g.hidden=b.hidden=true}},6600)}
let visitingUntil=0;
function cutCake(){if(!freeScene())return;momentBusy=true;target=null;const g=$('#groom'),b=$('#bride');g.hidden=b.hidden=false;g.style.left='43%';b.style.left='58%';g.style.top=b.style.top='49%';notify('伊薩克與白冥一起握住蛋糕刀，切下第一份甜蜜。');burst('heart',50,47,14);const knife=document.createElement('div');knife.className='cake-knife';knife.textContent='╱';fxLayer.append(knife);animate(knife,[{rotate:'-30deg',translate:'0 -12px'},{rotate:'30deg',translate:'0 15px'}],2200);later(()=>{knife.remove();g.style.left='45%';b.style.left='57%';g.style.top=b.style.top='24%';g.hidden=b.hidden=room!=='garden';momentBusy=false;const decorations=['白山茶','藍色愛心','小熊巧克力'];memories.cake=decorations[Math.floor(Math.random()*3)];story('你的婚禮蛋糕','你收到一塊綴著'+memories.cake+'的奶油蛋糕。白冥笑著說：「一起分享今天的幸福吧～」')},2600)}
function toastWith(who){memories.toast=true;burst('heart',positions[active].x,positions[active].y-8,7);story('一起碰杯',who==='夥伴'?'你和 '+guestName(1-active)+' 輕輕碰杯，把今天的幸福分享給彼此。':who==='孩子'?'兩個孩子拿起小小的果汁杯。狄安娜大聲說「乾杯！」薩維里也小心地碰了一下。':'伊薩克微微舉杯，白冥笑著說：「願你也有很多幸福的日子。」')}
const tray=document.createElement('div');tray.id='momentTray';tray.innerHTML='<button id="openMoments" aria-label="婚禮小互動">✦ 小互動</button><button id="stopBubbles" hidden>收起泡泡</button>';$('.stage').append(tray);
$('#openMoments').onclick=()=>{if(!freeScene())return;story(room==='garden'?'花園的小幸福':'宴會廳的小幸福','選一個喜歡的小互動，慢慢享受今天。',room==='garden'?[
 ['拿起泡泡籃',()=>{bubbleMode=true;momentDialog.close();$('#stopBubbles').hidden=false;notify('點擊地面會吹出泡泡，長按可以連續吹；仍可點地面移動。')}],
 ['敲響婚禮小鐘',()=>{if(Date.now()-lastBell<4000){$('#momentText').textContent='等鐘聲輕輕散去，再敲一次吧。';return}lastBell=Date.now();burst('petal',50,20,18);try{const ac=audioCtx||new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),v=ac.createGain();o.type='sine';o.frequency.value=880;o.connect(v);v.connect(ac.destination);v.gain.setValueAtTime(.12,ac.currentTime);v.gain.exponentialRampToValueAtTime(.001,ac.currentTime+2);o.start();o.stop(ac.currentTime+2)}catch{}$('#momentText').textContent='清亮的鐘聲響起，白山茶花瓣輕輕落下。'}],
 ['從花籃抽一句祝福',()=>{const wishes=['願你被溫柔以待','願相遇都有回音','願你的日常，也有小小的幸福','願有人陪你看每一次花開'];memories.fortune??=wishes[Math.floor(Math.random()*wishes.length)];story('花籤上的祝福',memories.fortune+'。這是今天屬於你的那一句。')}]
 ]:[['邀請新人切蛋糕',()=>{momentDialog.close();cutCake()}],['和新人碰杯',()=>toastWith('新人')],['和孩子喝果汁',()=>toastWith('孩子')],...(party===2?[['和同行夥伴碰杯',()=>toastWith('夥伴')]]:[])])};
$('#stopBubbles').onclick=()=>{bubbleMode=false;$('#stopBubbles').hidden=true};let bubbleTimer=null;
$('#world').addEventListener('pointerdown',e=>{if(!bubbleMode||!freeScene()||e.target.closest('button'))return;const r=$('#world').getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;burst('bubble',x,y,5);clearInterval(bubbleTimer);bubbleTimer=setInterval(()=>{if(freeScene()&&bubbleMode)burst('bubble',x,y,3);else clearInterval(bubbleTimer)},350)});
for(const event of ['pointerup','pointercancel','blur'])window.addEventListener(event,()=>clearInterval(bubbleTimer));
const originalSwitch=switchRoom;switchRoom=function(next){if(momentBusy)return;originalSwitch(next);ribbon.hidden=!(next==='garden'&&memories.ribbon===1);if(visitingUntil>Date.now()){for(const [id,x]of [['groom',43],['bride',57]]){const el=$('#'+id);el.hidden=next!=='hall';el.style.left=x+'%';el.style.top=next==='hall'?'36%':'24%'}}};
setInterval(()=>{if(visitingUntil&&Date.now()>visitingUntil){visitingUntil=0;for(const [id,x]of [['groom',45],['bride',57]]){const el=$('#'+id);el.hidden=room!=='garden';el.style.left=x+'%';el.style.top='24%'}}if(!freeScene()||document.hidden)return;ambientTick++;if(room==='garden'&&!visitingUntil){if(ambientTick%5===0)tour();else if(ambientTick%3===0){momentBusy=true;animate($('#bear'),[{translate:'0 0'},{translate:'18px 15px'},{translate:'0 0'}],3000);notify('鮑里斯悄悄看向甜點桌。伊薩克：「鮑里斯。」牠立刻若無其事地轉過頭。');later(()=>momentBusy=false,3100)}else coupleMoment(ambientTick%2?'veil':'bouquet')}},24000);
const leaveWithChoices=$('#leaveWedding').onclick;$('#leaveWedding').onclick=()=>{if(momentBusy){notify('等這個小互動結束，就可以拍照囉。');return}leaveWithChoices()};
const gardenProps=document.createElement('div');gardenProps.id='gardenProps';gardenProps.innerHTML='<button class="garden-prop bubble-basket" aria-label="拿取泡泡籃"><span>◌◦</span><small>泡泡籃</small></button><button class="garden-prop wedding-bell" aria-label="敲響婚禮小鐘"><span>♧</span><small>婚禮鐘</small></button><button class="garden-prop flower-lottery" aria-label="抽取花籤"><span>✿</span><small>花籤</small></button>';$('#world').append(gardenProps);
for(const [selector,index]of [['.bubble-basket',0],['.wedding-bell',1],['.flower-lottery',2]]){const b=gardenProps.querySelector(selector);b.onpointerdown=e=>e.stopPropagation();b.onclick=e=>{e.stopPropagation();if(!freeScene())return;$('#openMoments').click();$('#momentOptions').children[index]?.click()}}
const switchWithStories=switchRoom;switchRoom=function(next){switchWithStories(next);gardenProps.hidden=room!=='garden'};
$('#bear').style.pointerEvents='auto';$('#bear').setAttribute('role','button');$('#bear').setAttribute('tabindex','0');$('#bear').setAttribute('aria-label','摸摸鮑里斯');$('#bear').onpointerdown=e=>{e.stopPropagation();if(!freeScene())return;const r=$('#bear').getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;petBear(x>.65?(y>.45?'bow':'head'):'back')};$('#bear').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&freeScene()){e.preventDefault();petBear('head')}};

function weddingPlaces(){const visiting=visitingUntil>Date.now();if(room==='garden')return places.garden.filter(p=>!visiting||!['伊薩克','白冥'].includes(p.name));if(!visiting)return places.hall;return [...places.hall,...places.garden.filter(p=>['伊薩克','白冥'].includes(p.name)).map(p=>({...p,x:p.name==='伊薩克'?43:57,y:36,r:7}))]}
